version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  fastapi-app:
    build:
      context: . # Path to your Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    command: >
      sh -c "
      while ! nc -z rabbitmq 5672; do
        echo 'Waiting for RabbitMQ...';
        sleep 2;
      done;
      echo 'RabbitMQ is up. Starting FastAPI.';
      uvicorn main:app --host 0.0.0.0 --port 8000
      "
